name = "customaize"
compatibility_date = "2024-09-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "custom-aize-db"
database_id = "17e84a6f-e3fa-49fd-a6d4-4ce4ac8c1b6b"
migrations_dir = "./drizzle"
