#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if the src/app or src/pages directory exists
if [ -d "src/app" ] || [ -d "src/pages" ]; then
  pnpm lint-staged
else
  echo "Skipping lint-staged as no src/pages or src/app directory exists yet"
  # Still run lint-staged, but skip next lint
  git diff --cached --name-only | grep -E '\.(js|jsx|ts|tsx)$' | xargs -I {} pnpm prettier --write {}
fi
